tunnel: interview-helper
credentials-file: credentials.json

ingress:
  - hostname: "*.dhans.online"
    service: http://localhost:5000
  - hostname: dhans.online
    service: http://localhost:5000
  - service: http_status:404
